# Generated by Django 5.2.1 on 2025-06-03 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('duration', models.CharField(blank=True, max_length=50, verbose_name='Длительность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Полный курс',
                'verbose_name_plural': 'Полные курсы',
            },
        ),
        migrations.CreateModel(
            name='CoursePreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('direction', models.CharField(max_length=200, verbose_name='Направление')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='course_previews/', verbose_name='Изображение')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Курс превью',
                'verbose_name_plural': 'Курсы превью',
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название практики')),
                ('description', models.TextField(verbose_name='Описание практики')),
            ],
            options={
                'verbose_name': 'Практика',
                'verbose_name_plural': 'Практики',
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Преимущества')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(help_text='Используйте эмодзи', max_length=50, verbose_name='Иконка')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='main.course')),
            ],
            options={
                'verbose_name': 'Преимущества',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='CourseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='course_images/', verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.course')),
            ],
            options={
                'verbose_name': 'Изображение курса',
                'verbose_name_plural': 'Изображения курсов',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='preview',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_course', to='main.coursepreview'),
        ),
        migrations.CreateModel(
            name='CourseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_points', models.TextField(verbose_name='Итоги курса')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='main.course')),
            ],
            options={
                'verbose_name': 'Итоги курса',
                'verbose_name_plural': 'Итоги курсов',
            },
        ),
        migrations.CreateModel(
            name='NextSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_steps_text', models.TextField(verbose_name='Что дальше?')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='next_steps', to='main.course')),
            ],
            options={
                'verbose_name': 'Что дальше?',
                'verbose_name_plural': 'Что дальше?',
            },
        ),
        migrations.CreateModel(
            name='ProgramModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название модуля')),
                ('description', models.TextField(blank=True, verbose_name='Описание модуля')),
                ('lessons_count', models.PositiveSmallIntegerField(verbose_name='Количество уроков')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='main.course')),
            ],
            options={
                'verbose_name': 'Модуль программы',
                'verbose_name_plural': 'Модули программы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('description', models.TextField(blank=True, verbose_name='Описание урока')),
                ('practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.practice')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.programmodule')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название шага')),
                ('text', models.TextField(verbose_name='Содержание шага')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='main.lesson')),
            ],
            options={
                'verbose_name': 'Шаг урока',
                'verbose_name_plural': 'Шаги урока',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('description', models.TextField(blank=True, verbose_name='Характеристика преподавателя')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='instructors/', verbose_name='Фото')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='main.course')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
