# Generated by Django 5.2.1 on 2025-05-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('direction', models.CharField(max_length=200, verbose_name='Направление')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='course_previews/', verbose_name='Изображение')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Курс превью',
                'verbose_name_plural': 'Курсы превью',
            },
        ),
    ]
